# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 115a25578ec5dd718971a0a25b677a956fbcedd6f105867ea34c47fa84a6324250432d280be08a00d29112b8fdec5816900965a82d67de2c9a00de36c0dfc048

test:
  secret_key_base: 4f5881e21e2b0895b5de42cbaab653bd92b681ba69291111b3c6fd147c0c2c74e0943fc3255d82487d34bf761edfbd0e1e3dac0ec631621a032f9a2c239d4790

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
